In [1]:
import numpy as np 
import pandas as pd

In [2]:
a = 0.4
b = 0.6

2**3

8

In [3]:
import pandas as pd
import math

def ensemble_probability(p, n):
    """
    p : individual model accuracy
    n : number of models
    """
    
    results = []
    
    for k in range(n + 1):
        # Binomial probability
        prob = math.comb(n, k) * (p ** k) * ((1 - p) ** (n - k))
        
        # Majority condition
        majority = k > n / 2
        
        # Contribution to ensemble accuracy
        contribution = prob if majority else 0
        
        results.append({
            "Correct_Models (k)": k,
            "Probability_of_k": round(prob, 5),
            "Majority_Correct?": majority,
            "Contribution_to_Ensemble_Accuracy": round(contribution, 5)
        })
    
    df = pd.DataFrame(results)
    
    ensemble_acc = df["Contribution_to_Ensemble_Accuracy"].sum()
    
    print(f"\nEnsemble Accuracy = {round(ensemble_acc,5)}\n")
    
    return df

In [4]:
ensemble_probability(0.4, 5)

Ensemble Accuracy = 0.31744

,Correct_Models (k),Probability_of_k,Majority_Correct?,Contribution_to_Ensemble_Accuracy
0,0,0.07776,False,0.00000
1,1,0.25920,False,0.00000
2,2,0.34560,False,0.00000
3,3,0.23040,True,0.23040
4,4,0.07680,True,0.07680
5,5,0.01024,True,0.01024

In [ ]:
import pandas as pd
import itertools

def model_combinations(n_models, probabilities):
    """
    n_models: number of models (int)
    probabilities: list of model accuracies
                   length must equal n_models
    Example:
        model_combinations(2, [0.5, 0.5])
    """
    
    if len(probabilities) != n_models:
        raise ValueError("Length of probabilities must equal n_models")
    
    
    labels = [["A", "B"] for _ in range(n_models)]
    
    combinations = list(itertools.product(*labels))
    
    rows = []
    
    for combo in combinations:
        combined_prob = 1
        
        for i, outcome in enumerate(combo):
            if outcome == "A":  # correct
                combined_prob *= probabilities[i]
            else:               # wrong
                combined_prob *= (1 - probabilities[i])
        
        row = {f"Model{i+1}": combo[i] for i in range(n_models)}
        row["Combined_Probability"] = round(combined_prob, 4)
        
        rows.append(row)
    
    df = pd.DataFrame(rows)
    return df

In [7]:
model_combinations(3, [0.6, 0.4, 0.5])

  Model1 Model2 Model3  Combined_Probability
0      A      A      A                  0.12
1      A      A      B                  0.12
2      A      B      A                  0.18
3      A      B      B                  0.18
4      B      A      A                  0.08
5      B      A      B                  0.08
6      B      B      A                  0.12
7      B      B      B                  0.12